### ISSUE TITLE
Exporting Harmonics

### ISSUE THREAD

**Issue by eclab** [AndrewBelt/WaveEdit#8]
I'm building an additive synthesizer and would love to include wavetables; but my data format is of course harmonics.  Is there any way WaveEdit might be made to output the amplitudes of the harmonics of all the waves in a given wavetable?  It doesn't have to be any special binary format: text via fprintf would be just fine.

**Comment by AndrewBelt** [comment]
Can't you just load an arbitrary WAV in your software and compute its Fourier transform?

**Comment by eclab** [comment]
If I have to go that route I'll do a DFT on all the waves: but since your software already manipulates by harmonics, I was hoping it'd be as easy as doing a for-loop on the data and dumping it out.

**Comment by AndrewBelt** [comment]
It's open-source, you're welcome to add it to your copy.

**Comment by eclab** [comment]
I went ahead and built some code to convert the wav files to harmonics.  But this brings up another problem: waveeditonline.com doesn't seem to have a license requirement for posted WAV files.  When someone posts a file, this does not imply that the file is available for public use, because there's no license or declaration.  This is particularly problematic because these are *sound* files, which have their own special copyright requirements.

May I suggest that you add to WaveEdit a small splash screen, which appears first time that someone tries to upload a WAV file to waveeditonline.com, and which requires them to agree that any content they upload is licensed under a Creative Commons CC-BY license.  Then you can just state that all the files are CC-BY on the website.

BTW: WaveEdit seems to use up about 62% of my CPU while idle.  :-(

**Comment by miczac** [comment]
Re: CPU load: on what system are you? w/ v 1.1 on macos 10.12.6 I'm experiencing something similar.

**Comment by eclab** [comment]
OS X 10.13.6.

As to Creative Commons: feel free to disregard that, I'd not seen the notice when you upload a wav file.

**Comment by miczac** [comment]
You got a point regarding licensing. 
TBH, I didn't think of it, I can't even compile the SW to check things out.
The CPU-load issue was way worse in early releases, so I'm wondering what's the program actually doing?

**Comment by AndrewBelt** [comment]
@eclab Yes, there is a clear statement that wavetable uploads are CC0. You should ask Martin Doudoroff to put it on the website though.
Closing since I don't understand why you need the DFT exported instead of simply the WAV.
